In [1]:
import scipy.misc
import scipy.signal
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from PIL import ImageFilter
from PIL import ImageChops
from PIL import ImageStat
from scipy.ndimage.filters import gaussian_filter
from sklearn.preprocessing import StandardScaler

%matplotlib inline

In [2]:
II = np.zeros((550,4000))
for i in range(0,550):
    im = Image.open("./TrainImages/pos-"+str(i)+".pgm")
    II[i] = (np.array(im.getdata())).reshape(1,4000)
    


In [108]:
M = np.dot(II,II.T)
M.shape

(550, 550)

In [109]:
eV,EV = np.linalg.eigh(M)
rEV = np.dot(II.T,EV).T
rEV.shape

(550, 4000)

In [110]:
eV16 = np.flip(eV)[0:16]
rEV16 = np.flip(rEV)[0:16]

In [111]:
rEV16.shape

(16, 4000)

In [112]:
z = 0
for pc in rEV16:
    zz = str(z).zfill(2)
    pcI = pc.reshape((40,100))
    Image.fromarray(pcI,mode='L').save('./PCA16/PC'+zz+'.jpg')
    z += 1

In [113]:
Image.fromarray(rEV16[0].reshape((40,100)),mode='L').show()

In [47]:
im = Image.open("./TrainImages/pos-0.pgm")
im.show()
Image.fromarray(np.array(im.getdata()).reshape((1,4000)).reshape((40,100))).show()

In [114]:
Image.fromarray(II[1].reshape((40,100))).show()

In [64]:

U,S,V = np.linalg.svd((II.T - np.repeat(np.mean(II, axis=0),550,axis=0).reshape(550,4000).T))

In [65]:
EV16 = U[:16]
#x = StandardScaler().fit_transform(EV16)
EV16.shape

(16, 4000)

In [61]:
z = 0
for pc in EV16:
    zz = str(z).zfill(2)
    pcI = pc.reshape((40,100))
    Image.fromarray(pcI,mode='L').save('./PCA16/PC'+zz+'.jpg')
    z += 1

In [66]:
Image.fromarray(EV16[0].reshape((40,100)),mode='L').show()

In [27]:
np.repeat(np.mean(II, axis=1),4000,axis=0).reshape(550,4000)

array([[134.2505 , 134.2505 , 134.2505 , ..., 134.2505 , 134.2505 ,
        134.2505 ],
       [132.7515 , 132.7515 , 132.7515 , ..., 132.7515 , 132.7515 ,
        132.7515 ],
       [132.62575, 132.62575, 132.62575, ..., 132.62575, 132.62575,
        132.62575],
       ...,
       [125.56175, 125.56175, 125.56175, ..., 125.56175, 125.56175,
        125.56175],
       [127.32   , 127.32   , 127.32   , ..., 127.32   , 127.32   ,
        127.32   ],
       [126.93425, 126.93425, 126.93425, ..., 126.93425, 126.93425,
        126.93425]])

In [28]:
np.mean(II[0])

134.2505

In [34]:
II.shape

(550, 4000)

In [46]:
 ev, EV = np.linalg.eig(np.cov(II.T))

In [47]:
mmm = np.abs(EV[0].min())
iEV = (255.0 / (EV[0]+mmm).max() * ((EV[0]+mmm) - (EV[0]+mmm).min())).astype(np.uint8)

C:\Users\Edu\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: ComplexWarning: Casting complex values to real discards the imaginary part
  


In [49]:
EV[0]

array([ 1.19452302e-02+0.j, -8.43147372e-03+0.j, -1.55103052e-02+0.j, ...,
        1.94369866e-03+0.j, -6.95539649e-04+0.j, -7.96239565e-05+0.j])

In [77]:
a = np.mean(np.array(((1,5),(3,7))),axis=0).T
a

array([2., 6.])

In [73]:
II[0]

array([153., 153., 153., ..., 206., 224., 224.])

In [89]:
a = np.mean(II,axis=0).T
a.shape

(4000,)

In [91]:
np.array([a]*550).T.shape

(4000, 550)

In [92]:
II.T.shape

(4000, 550)

In [94]:
a = np.mean(II,axis=0).T
M = np.array([a]*550).T
U,S,V = np.linalg.svd(II.T - M)
U[0].shape

(4000,)

In [104]:
Image.fromarray(U[:,0].reshape((40,100)),mode='L').show()

In [100]:
U.T[0]

array([-0.01194523, -0.00843147,  0.01551031, ..., -0.0041644 ,
       -0.00571787, -0.00095645])

In [103]:
U.shape

(4000, 4000)

In [106]:
ev, EV = np.linalg.eig(np.cov(II.T))

In [110]:
EV = np.real(EV)
EV

array([[ 1.19452302e-02, -8.43147372e-03, -1.55103052e-02, ...,
         1.94369866e-03, -6.95539649e-04, -7.96239565e-05],
       [ 1.30032177e-02, -9.26106470e-03, -1.51366634e-02, ...,
         1.32745767e-04, -1.87349906e-04,  7.84451442e-05],
       [ 1.26675809e-02, -9.69225958e-03, -1.53666011e-02, ...,
         1.48428995e-04, -7.90538153e-05, -4.34585925e-05],
       ...,
       [ 3.92760679e-03,  1.31428174e-02,  7.44774564e-03, ...,
         1.50816699e-02,  7.93051871e-04,  3.66887307e-03],
       [ 3.97818357e-03,  1.27752352e-02,  7.13901916e-03, ...,
         1.47188794e-02, -4.66675220e-03,  8.07319030e-03],
       [ 4.75515650e-03,  1.27666145e-02,  7.86843101e-03, ...,
        -5.96919061e-03, -3.96647453e-02,  2.28800316e-02]])

In [117]:
ev = np.real(ev)
ev[:16]

array([2782474.09524329, 1259548.30336073,  857704.45042168,
        723435.44106076,  547671.30049036,  389782.1787916 ,
        376439.64461516,  318864.38738065,  289394.724291  ,
        277229.79983742,  232374.45701188,  220883.92276492,
        212140.63894074,  199940.00411265,  185566.95455471,
        175211.8946341 ])

In [114]:
EV.T[0].shape

(4000,)

In [127]:
Image.fromarray(EV.T[0].reshape((40,100)),mode='L').show()

In [125]:
ev[0]*EV.T[0]

array([33237.29348497, 36181.11626826, 35247.21577203, ...,
       10928.46414707, 11069.19274301, 13231.09976617])

In [126]:
np.dot(np.cov(II.T),EV.T[0])

array([33237.29348497, 36181.11626826, 35247.21577203, ...,
       10928.46414707, 11069.19274301, 13231.09976617])

In [128]:
ev.max() == ev[0]

True

In [129]:
np.cov(II).shape

(550, 550)